spring:
  application:
    name: quizzes
  datasource:
    username: root
    url: jdbc:postgresql://localhost:5432/company
    password: 123456789
  jackson:
    property-naming-strategy: SNAKE_CASE
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    hibernate:
      ddl-auto: update
    show-sql: true
  liquibase:
    enabled: true
server:
  port: 8084
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/