server:
  port: 8085
spring:
  application:
    name: notification
  rsocket:
    server:
      transport: websocket
      port: 7000
  data:
    mongodb:
      uri: mongodb://localhost:27017/notifications_db
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

