spring:
  application:
    name: gateway
  cloud:
    gateway:
      server:
        webflux:
          discovery:
            locator:
              enabled: true
              lower-case-service-id: true
          routes:
            - id: user
              uri: lb://USER
              predicates:
                - Path=/api/**
              filters:
                - StripPrefix=1

            - id: company
              uri: lb://COMPANY
              predicates:
                - Path=/api/**
              filters:
                - StripPrefix=1
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:9090/realms/spring-boot-mic
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/